---
  production: # 
    experiment_name: test_config_load_1
    include_date_in_results_folder: True

    dataset:
      dir: "test_datasets/tiffs_only/nyc_lc"
      splits: # leave empty for 0 split
        # - train
        # - val
        # - test
      gt_target_folders:
        # - input: 
        # - output: 
      
      # options for specifying files to loads
      # landsat 8 provided as example
      # https://torchgeo.readthedocs.io/en/latest/tutorials/custom_raster_dataset.html
      inputs:
        filename_glob: "ortho_*.tif"
        filename_regex:
        date_format: 
        is_image: False
        separate_files: False
        all_bands: ["Green", "Red", "NIR"]
        rgb_bands: ["Green", "Red", "NIR"]

      targets:
        filename_glob: "landcover*.tif"
        # filename_regex:
        # date_format: "%Y%m%dT%H%M%S"
        is_image: False
        separate_files: False
      
      # only used if dataset.splits is empty
      # specify sampler to use: dataset splt (0,1)
      
      splits_to_use:
        train: 
          random: 0.6
        val: 
          random: 0.2
        test:
          grid: 0.2
...
